# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('esperando', 'esperando'), ('enviando', 'enviando'), ('entregado', 'entregado')], max_length=50)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.Anuncio')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.Oferta')),
            ],
        ),
    ]
